#!/bin/sh
branch="$(git symbolic-ref --short HEAD)"
if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
  echo "❌ Pushing directly to '$branch' is not allowed. Please use a feature branch."
  exit 1
fi